locale: 'zh_CN'
#shared-data-sources:
#  common:
#    type: hikari
#    properties:
#      jdbcUrl: 'jdbc:mysql://localhost:3306/test?useSSL=false'
#      username: 'root'
#      password: '123456'
#      maximumPoolSize: 5
# mongodb-clients:
#  common:
#    url: 'mongodb://localhost:27017'
#redis-clients:
#  common:
#    url: 'redis://localhost:6379'