locale: 'zh_CN'
shared-data-sources: {}
#mongodb-clients:
#  common:
#    url: 'mongodb://localhost:27017'
#  common:
#    type: hikari
#    config:
#      jdbcUrl: 'jdbc:mysql://localhost:3306/test?useSSL=false'
#      username: 'root'
#      password: '123456'
#      maximumPoolSize: 5